"""
Django settings for f4cloud project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

import os
import configparser

config = configparser.ConfigParser()
config.read('config.ini')

# AWS Settings
AWS_ACCESS_KEY_ID = config['AWS']['ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = config['AWS']['SECRET_ACCESS_KEY']
IDENTITY_POOL_ID = config['AWS']['IDENTITY_POOL_ID']
ACCOUNTID = config['AWS']['ACCOUNTID']
DEFAULT_REGION_NAME = config['AWS']['DEFAULT_REGION_NAME']
DEFAULT_USER_POOL_ID = config['AWS']['DEFAULT_USER_POOL_ID']
DEFAULT_USER_POOL_APP_ID = config['AWS']['DEFAULT_USER_POOL_APP_ID']
S3_BUCKET_ID = config['AWS']['S3_BUCKET_ID']
DEFAULT_CONFIG = {
    'region_name': DEFAULT_REGION_NAME,
    'aws_access_key_id': AWS_ACCESS_KEY_ID,
    'aws_secret_access_key': AWS_SECRET_ACCESS_KEY
}
DEFAULT_USER_POOL_LOGIN_PROVIDER = 'cognito-idp.{0}.amazonaws.com/{1}'.format(
    DEFAULT_REGION_NAME, DEFAULT_USER_POOL_ID
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0xvkwrbq*-kopr4^$mlyd6(-90hv8ezl=6by28g0glysi(x@47'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cognito_jwt',
    'rest_framework',
    'users.apps.UsersConfig',
    'files.apps.FilesConfig',
    'folders.apps.FoldersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'f4cloud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'f4cloud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config['DB']['ENGINE'],
        'HOST': config['DB']['HOST'],
        'PORT': config['DB']['PORT'],
        'NAME': config['DB']['NAME'],
        'USER': config['DB']['USER'],
        'PASSWORD': config['DB']['PASSWORD'],
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
